// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventIngressClient is the client API for EventIngress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventIngressClient interface {
	ReportEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type eventIngressClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngressClient(cc grpc.ClientConnInterface) EventIngressClient {
	return &eventIngressClient{cc}
}

func (c *eventIngressClient) ReportEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/server.EventIngress/reportEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventIngressServer is the server API for EventIngress service.
// All implementations must embed UnimplementedEventIngressServer
// for forward compatibility
type EventIngressServer interface {
	ReportEvent(context.Context, *Event) (*emptypb.Empty, error)
	mustEmbedUnimplementedEventIngressServer()
}

// UnimplementedEventIngressServer must be embedded to have forward compatible implementations.
type UnimplementedEventIngressServer struct {
}

func (UnimplementedEventIngressServer) ReportEvent(context.Context, *Event) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportEvent not implemented")
}
func (UnimplementedEventIngressServer) mustEmbedUnimplementedEventIngressServer() {}

// UnsafeEventIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngressServer will
// result in compilation errors.
type UnsafeEventIngressServer interface {
	mustEmbedUnimplementedEventIngressServer()
}

func RegisterEventIngressServer(s grpc.ServiceRegistrar, srv EventIngressServer) {
	s.RegisterService(&EventIngress_ServiceDesc, srv)
}

func _EventIngress_ReportEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngressServer).ReportEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.EventIngress/reportEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngressServer).ReportEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// EventIngress_ServiceDesc is the grpc.ServiceDesc for EventIngress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.EventIngress",
	HandlerType: (*EventIngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "reportEvent",
			Handler:    _EventIngress_ReportEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/proto/server.proto",
}
